models/friend.py
import time
from mongoengine import *
import uuid
import json
from models import Model
from models.user import User
from models.group import Group

class Friend(Document, Model):
    __fields__ = [
        'user1',
        'user2'
    ]

    user1 = ReferenceField(User)
    user2 = ReferenceField(User)
    #
    # @classmethod
    # def add(cls, form, u1, u2):
    #     t = Note(
    #         user=u,
    #         group=g
    #     )
    #     t.save()
    #     print('model Note insert', t.title)
    #     d = dict(
    #         title=t.title,
    #         note_id=t.note_id,
    #         updated_time=t.updated_time,
    #     )
    #     return json.dumps(d)

models/group.py
import time
from mongoengine import *
import uuid
import json
from models import Model
from models.user import User


class Group(Document, Model):
    __fields__ = [
        'group_id',
        'name',
        'icon',
        'intro',
        'updated_time',
        'admin',
        'users',

    ]

    group_id = StringField(required=True)
    name = StringField(max_length=20)
    intro = StringField(max_length=50)
    updated_time = IntField()
    admin = ReferenceField(User)
    user = ReferenceField(User)
    icon = StringField(max_length=50)
    users = ListField(ReferenceField(User, reverse_delete_rule=PULL))

    @classmethod
    def addGroup(cls, form, u):
        t = Group(
            name=form.get('name', ''),
            intro=form.get('intro', ''),
            group_id=str(uuid.uuid1()),
            updated_time=int(time.time()),
            icon='/static/images/clock.gif',
            admin=u,
            user=u,
        )
        userlist = [u]
        t.users = userlist
        t.save()
        print('model Group add', t.name)
        d = dict(
            name=t.name,
            group_id=t.group_id,
            intro=t.intro,
            admin=t.admin.user_id,
            icon=t.icon,
        )
        return json.dumps(d)

    @classmethod
    def participateGroup(cls, form, u):
        gid = form.get('group_id', '')
        print("model group participate gid", gid)
        g = Group.get_one_by(group_id=gid)
        if u not in g.users:
            g.users.append(u)
        else:
            print('用户已存在于群组')
        g.save()
        print("model group userlist", g.users)
        return ''


    @classmethod
    def getpall(cls, u):
        t_list = Group.objects(users__all=[u])
        print(list)
        dict_all = []
        for l in t_list:
            td = {}
            # len(cls.__fields__)有多少个属性项
            for i in range(len(cls.__fields__)):
                # 如果这个属性是一个类，判断
                flag1 = isinstance(l[cls.__fields__[i]], Model)
                if flag1 is False:
                    td[cls.__fields__[i]] = l[cls.__fields__[i]]

                if cls.__fields__[i] == 'users':
                    td[cls.__fields__[i]] = [a.icon for a in l[cls.__fields__[i]]]
                if cls.__fields__[i] == 'admin':
                    td[cls.__fields__[i]] = l[cls.__fields__[i]].name
            # td = {'todo_id': l.todo_id,
            #       'title': l.title,
            #       'done':l.done,
            #       'dead_line':l.dead_line}
            dict_all.append(td)
        print("!!Model getpall", dict_all)

        return json.dumps(dict_all)

models/note.py
import time
from mongoengine import *
import uuid
import json
from models import Model
from models.user import User
from models.group import Group

class Note(Document, Model):
    __fields__ = [
        'note_id',
        'title',
        'updated_time',
        'user',
        'group'
    ]

    note_id = StringField(required=True)
    title = StringField(max_length=70)
    updated_time = IntField()
    user = ReferenceField(User)
    group = ReferenceField(Group)

    @classmethod
    def inserNote(cls, form, u, g):
        t = Note(
            title=form.get('title', ''),
            note_id=str(uuid.uuid1()),
            updated_time=int(time.time()),
            user=u,
            group=g
        )
        t.save()
        print('model Note insert', t.title)
        d = dict(
            title=t.title,
            note_id=t.note_id,
            updated_time=t.updated_time,
        )
        return json.dumps(d)

    @classmethod
    def delNote(cls, j):
        noteid = j['note_id']
        # ??????????
        flag = Note.objects(note_id=noteid).delete()
        print('model note', 'delNote', flag)
        if flag != 1:
            return 'wrong delete'
        return json.dumps(flag)

routes/friend.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    send_from_directory,
)

from models.chat import Chat
from models.todo import Todo
from routes.index import current_user
from models.user import User
from utils import log
import json
main = Blueprint('friend', __name__)

@main.route("/")
def index():
    u = current_user()
    if u is not None:
        # 若有用户
        return render_template("friend.html", user=u)
    else:
        # 若无用户
        return redirect(url_for('index.index'))

@main.route("/all")
def all():
    u=current_user()
    list = User.get_all_friend(u)
    return (list)

@main.route("/add", methods=['POST'])
def add():
    form = request.form
    print('!!friend add form', form)
    u = current_user()
    t = User.addfriend(form, u)
    return redirect(url_for('.index'))

@main.route("/chat", methods=['POST'])
def chat():
    u = current_user()
    form = request.form
    print('!!friend chat form', form)
    t = Chat.add(form, u.user_id, form['userto'])
    return t

@main.route("/chatall", methods=['POST'])
def chatall():
    u = current_user()
    form = request.get_json()
    print('!!friend chatall form', form)
    t = Chat.chatall(u.user_id, form['userto'], None)
    return t

@main.route("/chatre", methods=['POST'])
def chatre():
    u = current_user()
    form = request.get_json()
    print('!!friend chatre form', form)
    t = Chat.chatall(u.user_id, form['userto'], form['last'])
    return t
    pass

routes/g_index.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    send_from_directory,
)

from models.group import Group
from models.todo import Todo
from routes.index import current_user
from utils import log
main = Blueprint('g_index', __name__)

@main.route('/<gid>')
@main.route('/<gid>/')
def index(gid):
    u = current_user()
    g = Group.get_one_by(group_id=gid)
    print(g)
    return render_template("g_index.html", user=u, group=g)

@main.route("/<gid>/all")
def all(gid):
    g = Group.get_one_by(group_id=gid)
    t_list = Todo.getAll(None, g)
    return (t_list)

@main.route("/<gid>/check", methods=['POST'])
def check(gid):
    json = request.get_json()
    g = Group.get_one_by(group_id=gid)
    print('!!check json', json)
    u = current_user()
    result_id = Todo.toggleTodoGroup(json, u, g)
    return result_id

@main.route("/<gid>/add", methods=['POST'])
def add(gid):
    form = request.form
    print('!!add form', form)
    # ImmutableMultiDict([('title', '的撒发射点法大师傅大师傅')])
    u = current_user()
    # u代表user
    g = Group.get_one_by(group_id=gid)
    t = Todo.inserTodo(form, u, g)
    s = '.' + gid
    return redirect(url_for(".index", gid=gid))

@main.route("/<gid>/reorder", methods=['POST'])
def reorder(gid):
    form = request.form
    print('!!reorder form', form)
    result_id = Todo.reorderTodo(form)
    return redirect(url_for('.index', gid=gid))

routes/g_members.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    send_from_directory,
)
import json
from models.group import Group
from models.todo import Todo
from models.tag import Tag
from routes.index import current_user
main = Blueprint('g_members', __name__)

@main.route('/<gid>/members')
def index(gid):
    u = current_user()
    g = Group.get_one_by(group_id=gid)
    print(g)
    return render_template("g_members.html", user=u, group=g)

@main.route('/<gid>/members/all')
def all(gid):
    u = current_user()
    gu = Group.get_one_by(group_id=gid).users
    list = []
    for g in gu:
        t = dict(
            name=g.name,
            icon=g.icon,
            email=g.email
        )
        list.append(t)
    print(list)
    return json.dumps(list)

routes/g_notes.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    send_from_directory,
)

from models.note import Note
from models.todo import Todo
from models.group import Group
from routes.index import current_user

from utils import log
main = Blueprint('g_notes', __name__)

@main.route('/<gid>/notes')
def index(gid):
    u = current_user()
    g = Group.get_one_by(group_id=gid)
    print(g)
    return render_template("g_notes.html", user=u, group=g)

@main.route("/<gid>/notes/all")
def all(gid):
    u=current_user()
    g = Group.get_one_by(group_id=gid)
    list = Note.getAll(None, g)
    return (list)

@main.route("/<gid>/notes/add", methods=['POST'])
def add(gid):
    form = request.form
    print('!!note add form', form)
    u = current_user()
    g = Group.get_one_by(group_id=gid)
    t = Note.inserNote(form, u, g)
    return t

routes/g_performance.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    send_from_directory,
)
import json
from models.group import Group
from models.todo import Todo
from models.tag import Tag
from routes.index import current_user
main = Blueprint('g_performance', __name__)

@main.route('/<gid>/performance')
def index(gid):
    u = current_user()
    g = Group.get_one_by(group_id=gid)
    print(g)
    return render_template("g_performance.html", user=u, group=g)

@main.route('/<gid>/performance/all')
def all(gid):
    u = current_user()
    gu = Group.get_one_by(group_id=gid).users
    list = []
    for g in gu:
        t = dict(
            name=g.name,
            icon=g.icon,
            email=g.email,
            performance=g.performance
        )
        list.append(t)

    def takep(u):
        return u['performance']
    list.sort(key=takep, reverse=True) # 降序
    print(list)
    return json.dumps(list)

routes/g_projects.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    send_from_directory,
)

from models.group import Group
from models.todo import Todo
from models.project import Project
from routes.index import current_user
main = Blueprint('g_projects', __name__)

@main.route('/<gid>/projects')
def index(gid):
    u = current_user()
    g = Group.get_one_by(group_id=gid)
    print(g)
    return render_template("g_projects.html", user=u, group=g)

@main.route('/<gid>/projects/all')
def all(gid):
    u = current_user()
    g = Group.get_one_by(group_id=gid)
    print(g)
    list = Project.getAll(None, g)
    return (list)

@main.route("/<gid>/projects/add", methods=['POST'])
def add(gid):
    form = request.form
    print('!!project add form', form)
    # ImmutableMultiDict([('title', '的撒发射点法大师傅大师傅')])
    u = current_user()
    g = Group.get_one_by(group_id=gid)

    t = Project.inserProject(form, u, g)
    return t

routes/g_tags.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    send_from_directory,
)

from models.group import Group
from models.todo import Todo
from models.tag import Tag
from routes.index import current_user
main = Blueprint('g_tags', __name__)

@main.route('/<gid>/tags')
def index(gid):
    u = current_user()
    g = Group.get_one_by(group_id=gid)
    print(g)
    return render_template("g_tags.html", user=u, group=g)

@main.route('/<gid>/tags/all')
def all(gid):
    u = current_user()
    g = Group.get_one_by(group_id=gid)
    print(g)
    list = Tag.getAll(None, g)
    return (list)

@main.route("/<gid>/tags/add", methods=['POST'])
def add(gid):
    form = request.form
    print('!!tag add form', form)
    u = current_user()
    g = Group.get_one_by(group_id=gid)
    t = Tag.inserTag(form, u, g)
    return t

routes/groups.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    send_from_directory,
)

from models.group import Group
from models.todo import Todo
from routes.index import current_user
from utils import log
main = Blueprint('groups', __name__)

@main.route("/")
def index():
    u = current_user()
    if u is not None:
        # 若有用户
        return render_template("groups.html", user=u)
    else:
        # 若无用户
        return redirect(url_for('index.index'))

@main.route("/all")
def all():
    u = current_user()
    list = Group.getAll(u, None)
    return list

'''得到所有参加的群组'''
@main.route(("/p_all"))
def p_all():
    u = current_user()
    list = Group.getpall(u)
    return list

@main.route("/add", methods=['POST'])
def add():
    form = request.form
    print('!!group add form', form)
    u = current_user()
    g = Group.addGroup(form, u)
    return g

'''用户参加群组，暂时的方法是通过groupid参加'''
@main.route('/participate', methods=['POST'])
def participate():
    form = request.form
    print("!!group participate form", form)
    u = current_user()
    g = Group.participateGroup(form, u)
    return g

routes/notes.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    send_from_directory,
)

from models.note import Note
from models.todo import Todo
from routes.index import current_user
from utils import log
main = Blueprint('notes', __name__)

@main.route("/")
def index():
    u = current_user()
    if u is not None:
        # 若有用户
        return render_template("notes.html", user=u)
    else:
        # 若无用户
        return redirect(url_for('index.index'))

@main.route("/all")
def all():
    u=current_user()
    list = Note.getAll(u, None)
    return (list)

@main.route("/add", methods=['POST'])
def add():
    form = request.form
    print('!!note add form', form)
    u = current_user()
    t = Note.inserNote(form, u, None)
    return t

@main.route("/delete", methods=['POST'])
def delete():
    json = request.get_json()
    print('!!note delete json', json['note_id'])
    result_status = Note.delNote(json)
    print('!!note delete json', result_status)
    return result_status

routes/projects.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    send_from_directory,
)

from models.project import Project
from models.todo import Todo
from routes.index import current_user
from utils import log
main = Blueprint('projects', __name__)

@main.route("/")
def index():
    u = current_user()
    if u is not None:
        # 若有用户
        return render_template("projects.html", user=u)
    else:
        # 若无用户
        return redirect(url_for('index.index'))

@main.route("/all")
def all():
    u = current_user()
    list = Project.getAll(u, None)
    return (list)

@main.route("/add", methods=['POST'])
def add():
    form = request.form
    print('!!project add form', form)
    # ImmutableMultiDict([('title', '的撒发射点法大师傅大师傅')])
    u = current_user()
    t = Project.inserProject(form, u, None)
    return t

'''本函数注意在删除项目的时候，项目内todo也全部删除'''
@main.route("/delete", methods=['POST'])
def delete():
    json = request.get_json()
    print('!!project delete json', json['project_id'])
    Todo.delTodobyProject(json['project_id'])
    result_status = Project.delProject(json)
    print(result_status)
    return result_status

@main.route("/gettodoinproject", methods=['POST'])
def getTodoInProject():
    json = request.get_json()
    print('!!project gettodoinproject json', json['project_id'])
    list = Todo.getTodobyProject(json['project_id'])
    print('!!project gettodoinproject list', list)
    return list

routes/tags.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    send_from_directory,
)

from models.tag import Tag
from models.todo import Todo
from routes.index import current_user
from utils import log
main = Blueprint('tags', __name__)

@main.route("/")
def index():
    u = current_user()
    if u is not None:
        # 若有用户
        return render_template("tags.html", user=u)
    else:
        # 若无用户
        return redirect(url_for('index.index'))
@main.route("/all")
def all():
    u = current_user()
    list = Tag.getAll(u, None)
    return (list)

@main.route("/add", methods=['POST'])
def add():
    form = request.form
    print('!!tag add form', form)
    u = current_user()
    t = Tag.inserTag(form, u, None)
    return t

'''本函数注意在删除tag的时候，包含tag的todo只删除tag字段'''
@main.route("/delete", methods=['POST'])
def delete():
    json = request.get_json()
    print('!!tag delete json', json['tag_id'])
    result_status = Tag.delTag(json)
    print(result_status)
    return result_status

@main.route("/gettodointag", methods=['POST'])
def getTodoInTag():
    json = request.get_json()
    print('!!tag gettodointag json', json['tag_id'])
    list = Todo.getTodobyTag(json['tag_id'])
    print('!!tag gettodointag list', list)
    return list

templates/friend.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>自在Todo</title>
    <link rel="shortcut icon" href="/static/images/man.png">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="/static/css/materialize.css">
    <link href="https://cdn.bootcss.com/material-design-icons/3.0.1/iconfont/material-icons.min.css" rel="stylesheet">
    <!-- <link href="https://cdn.bootcss.com/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css"
        rel="stylesheet"> -->

    <link rel="stylesheet" href="/static/css/jquery.datetimepicker.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <style>
        .members_container {
            width: 75%;
        }

        .small {
            width: 20px;
            height: 20px;
        }
    </style>
</head>

<body>

    <!-- <div class="progress hide jindutiao">
        <div class="indeterminate"></div>
    </div> -->

    <!-- 左侧边栏 -->
    <ul class="sidenav sidenav-fixed">
        <li>
            <div class="user-view">
                <div class="background">
                    <img src="/static/images/moutain.jpg">
                </div>
                <a href="#user"><img class="circle" src="{{ user.icon }}"></a>
                <a href="#name"><span class="white-text name">{{ user.name }}</span></a>
                <a href="#email"><span class="white-text email">{{ user.email }}</span></a>
            </div>
        </li>
        <li><a href="/" class='waves-effect'><i class="material-icons">done_all</i>任务<span
                    class="new badge red todobadge" data-badge-caption="todo">0</span></a></li>
        <li><a href="/projects" class='waves-effect'><i class="material-icons">folder</i>项目</a></li>
        <li><a href="/tags" class='waves-effect'><i class="material-icons">bookmark</i>标签</a></li>
        <li><a href="/notes" class='waves-effect'><i class="material-icons">receipt</i>便签</a></li>
        <li>
            <div class="divider"></div>
        </li>


        <li><a href="/groups" class='waves-effect'><i class="material-icons">group</i>群组</a></li>
        <li><a href="/friend" class='waves-effect'><i class="material-icons">email</i>消息</a></li>

        <li><a class="subheader"></a></li>
        <li><a class="subheader"></a></li>
        <li><a class="subheader"></a></li>

        <li>
            <div class="divider"></div>
        </li>
        <li><a href="/setting" class='waves-effect'><i class="material-icons">build</i>设置</a></li>
        <li>
            <div class="divider"></div>
        </li>
    </ul>

    <div class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <a href="#!" class="brand-logo"><i class="material-icons">cloud</i>Logo</a>
                <ul class="right">
                    <li>当前：个人工作空间</li>
                    <li><a href="sass.html"><i class="material-icons">search</i></a></li>
                    <li><a href="badges.html"><i class="material-icons">view_module</i></a></li>
                    <li><a href="collapsible.html"><i class="material-icons">refresh</i></a></li>
                    <li><a href="mobile.html"><i class="material-icons">power_settings_new</i></a></li>
                </ul>
            </div>
        </nav>
    </div>

    <!-- 弹出来的详细编辑页 -->
    <div id="modal1" class="modal">
        <div class="modal-content">
            <h4>新加好友</h4>
            <form action='{{ url_for("friend.add") }}' method="post" autocomplete="off">

                <div class="modal-box">
                    用户账号：
                    <input type="text" id="id-modal-title" name='email' />
                    <!-- <input type="hidden" id='hideinput' name='project_id' value="" /> -->
                </div>

        </div>

        <div class="modal-footer">
            <!-- <a href="#!" class=" waves-effect waves-green btn-flat">
            </a> -->
            <input type="submit" class='modal-close btn' value="添加">
            </form>

        </div>
    </div>

    <div id="modal2" class="modal">
        <div class="modal-content">
            <h4>聊天</h4>
            <div class="collection chat_container">

            </div>

            <form action='{{ url_for("friend.chat") }}' method="post" autocomplete="off" id=id-newform>

                <div class="modal-box">
                    发送消息：
                    <input type="text" id="id-modal-title2" name='title' />
                    <input id="id-modal-userto" name='userto' value="3333" type="hidden" />

                    <!-- <input type="hidden" id='hideinput' name='project_id' value="" /> -->
                </div>

        </div>

        <div class="modal-footer">
            <!-- <a href="#!" class=" waves-effect waves-green btn-flat">
            </a> -->
            <input type="submit" class='btn' value="发送">
            </form>

        </div>
    </div>



    <main>
        <div class="btn_control">
            <a class="waves-effect waves-light btn modal-trigger" href="#modal1">添加好友</a>


        </div>

        <ul class="collection members_container">

        </ul>





    </main>


    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="/static/js/materialize.js"></script>
    <script>
        M.AutoInit();
        $(document).ready(function () {
            $('.sidenav').sidenav();
            $('input#input_text').characterCounter();

            $("#id-newform").submit(function (e) {
                e.preventDefault(); // avoid to execute the actual submit of the form.
                var form = $(this);
                var url = form.attr('action');
                $.ajax({
                    type: "POST",
                    url: url,
                    data: form.serialize(), // serializes the form's elements.
                    success: function (data) {
                        m = JSON.parse(data)
                        $('#id-modal-title2').val("");
                        log(m); // show response from the script.
                        $('.chat_container').append(
                            `
                            <a href="#!" class="collection-item blue-text"><img src=${m.userfromicon} alt="" class='small'>
                            ${m.updated_time}@${m.title}
                            
                            </a>
                            `
                        )
                    }
                });
            });
        });
        var log = function () {
            console.log.apply(console, arguments)
        }
        var timetodatem = function (unixtime) {
            let date = new Date(unixtime * 1000);
            Y = date.getFullYear() + '-';
            M = (date.getMonth() + 1 < 10 ? '0' + (date.getMonth() + 1) : date.getMonth() + 1) + '-';
            D = date.getDate() + ' ';
            h = date.getHours() + ':';
            m = date.getMinutes() + ':';
            s = date.getSeconds();
            ttt = Y + M + D + h + m + s;
            // 简便方法
            // t2 = date.toLocaleString();
            // log(t2);
            console.log(Y + M + D + h + m + s);
            return ttt;
        }



        //普通表单
        $.ajax({
            type: 'GET',
            url: './all',
            success: function (r) {
                r = JSON.parse(r)
                log(r)
                inserMembers(r)
            }
        }).fail(function (jqXHR, textStatus, errorThrown) {
            //错误信息
            console.log("AJAX FAIL")
        });

        let inserMembers = function (members) {
            for (let i in members) {
                log(i, ':', members[i])

                $('.members_container').append(
                    `
                    <li class="collection-item avatar" data-id=${members[i].user_id}>
                    <img src="${members[i].icon}" alt="" class="circle">
                    <span class="title">${members[i].name}</span>
                    <p>${members[i].email} <br>
                    </p>
                    <a class="waves-effect waves-light btn modal-trigger" href="#modal2">发消息</a>
                    </li>
                    `

                    //<i class="material-icons small-icon left reorderbtn">reorder</i>
                )
            }
        }




    </script>
    <script>
        $('.members_container').click(function (event) {
            target = event.target;
            m_id = $(target).parents("li").attr('data-id');

            if (target.classList.contains('btn')) {
                clearInterval()
                console.log(m_id)
                currentuser = '{{user.name}}'
                console.log(currentuser)
                $('#id-modal-userto').attr("value", m_id)
                $('.chat_container').empty()
                $.ajax({
                    type: 'POST',
                    url: './chatall',
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify({
                        'userto': m_id,
                    }),
                    success: function (r) {
                        console.log(r)
                        let cct = $('.chat_container')
                        let last = 0
                        for (let i in r) {
                            if (r[i].userfrom != currentuser) {
                                last = r[i].updated_time
                                cct.append(
                                    `
                                    <a href="#!" class="collection-item red-text"><img src=${r[i].userfromicon} alt="" class='small'>
                                    ${r[i].updated_time}@${r[i].title}
                                        </a>
                                    `
                                )
                            }
                            else {
                                last = r[i].updated_time
                                cct.append(
                                    `
                                    <a href="#!" class="collection-item blue-text"><img src=${r[i].userfromicon} alt="" class='small'>
                                    ${r[i].updated_time}@${r[i].title}</a>
                                    `
                                )

                            }

                        }
                        window.setInterval(function () {
                            /// call your function here
                            $.ajax({
                                type: 'POST',
                                url: './chatre',
                                dataType: "json",
                                contentType: "application/json; charset=utf-8",
                                data: JSON.stringify({
                                    'last': last,
                                    'userto': m_id,
                                }),
                                success: function (r) {
                                    console.log(r)
                                    let cct = $('.chat_container')
                                    for (let i in r) {
                                        if (r[i].userfrom != currentuser) {
                                            last = r[i].updated_time
                                            cct.append(
                                                `
                                                <a href="#!" class="collection-item red-text"><img src=${r[i].userfromicon} alt="" class='small'>
                                                ${r[i].updated_time}@${r[i].title}</a>
                                                `
                                            )
                                        }
                                        // else {
                                        //     last = r[i].updated_time
                                        //     cct.append(
                                        //         `
                                        //         <a href="#!" class="collection-item blue-text">${r[i].updated_time}@${r[i].title}</a>
                                        //         `
                                        //     )

                                        // }

                                    }
                                }
                            }).fail(function (jqXHR, textStatus, errorThrown) {
                                //错误信息
                                console.log("AJAX FAIL FAIL")
                            });
                        }, 1000);

                    }
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    //错误信息
                    console.log("AJAX FAIL")
                });
            }

        })
    </script>
</body>

</html>